services:
  db:
    image: postgres:16-alpine
    container_name: forensics_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: forensics
      POSTGRES_PASSWORD: forensics
      POSTGRES_DB: forensics
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: